### ISSUE TITLE
Need some documentation on how to run

### ISSUE THREAD

**Issue by saibotsivad** [TehShrike/state-router-example#1]
I assume it's just

```
git clone REPO
cd REPO
npm install .
npm build
```

maybe? Have to have browserify installed with -g probably? Maybe watchify also?

I was having trouble with npm this morning, so I couldn't verify that flow for sure, but it looks correct.

**Comment by TehShrike** [comment]
It should be `npm run build` - and yeah, it does need browserify installed globally at the moment.

After I implement adding new topics and tasks, I'll have to decide how I want to distribute this version along with the riotjs/html-template implementations.  I was originally thinking of having a different branch for each implementation, but I'm wondering now if I'd just put each one in a different subdirectory inside the repo.

Anyways, at that point I'll update the readme and make it friendly for people to poke at locally.

**Comment by ArtskydJ** [comment]
I ran it by doing:

``` bash
npm install state-router-example
npm install st -g #st is a static file server
cd node_modules\state-router-example
npm run build
st -p 80
```

But then it ends up in a `node_modules` folder. But if you're just going to try it out, that's probably not a big deal.

**Comment by TehShrike** [comment]
I should probably set up a prepublish script to do the building so that you don't have to know the build command and can just install it wherever.
