### ISSUE TITLE
Getting a 404 for rsvp.js.map

### ISSUE THREAD

**Issue by saibotsivad** [TehShrike/state-router-example#2]
Under the assumption that the build step is correct in https://github.com/TehShrike/state-router-example/issues/1

When I launch using `python -m SimpleHTTPServer 8000` then the console.log says:

```
Initializing dummy data
GET http://localhost:8000/rsvp.js.map 404 (File not found)
```

**Comment by TehShrike** [comment]
Huh.  I'm not sure what would have caused a GET for that path, rsvp.js shouldn't ever be referenced directly outside of being packaged in with browserify.

**Comment by TehShrike** [comment]
Closed because I can't reproduuuuuuuce
